bcgov/MOH-FPC-Enrolment

msp-service/src/cache.js, msp-service/src/index.js
=> Cache service

fpcare/package.json, fpcare/src/VERSION.generated.ts, fpincome/CHANGELOG.md, fpincome/package-lock.json, fpincome/package.json, fpincome/src/version.GENERATED.ts
=> Version files

fpcare/src/version.js, fpincome/src/version.js
=> chore: version.js update

fpcare/src/app/modules/geocoder/components/geocoder-input/geocoder-input.component.spec.ts
=> Fix Geocoder component test

fpcare/package-lock.json, fpcare/package.json, fpcare/src/VERSION.generated.ts, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html
=> Mail address

fpincome/src/app/income-review/pages/income/income.component.ts
=> fix: clear validator when not required

doc/SetupDevEnvironment.md, doc/SetupToolsEnvironment.md, openshift/templates/nsp-fpcare-to-maximus-dev.yaml.old, openshift/templates/nsp-fpcare-to-maximus-test.yaml.old, openshift/templates/nsp-fpincome-to-maximus-dev.yaml.old, openshift/templates/nsp-fpincome-to-maximus-test.yaml.old, openshift/templates/nsp-tools.yaml.old, openshift/templates/nsp.yaml.old, openshift/templates/quickstart.yaml
=> Networkpolicy changes

doc/SetupDevEnvironment.md, doc/SetupTestEnvironment.md, doc/SetupToolsEnvironment.md
=> chore: update documentation

address-service/src/index.js, fpcare/src/app/models/person.model.ts, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.ts
=> fix: address doctor validation

address-service/src/index.js
=> fix: typo in code

fpincome/src/app/income-review/component/collection-notice/collection-notice.component.ts
=> fix: add set focus when modal shows

fpincome/src/app/income-review/component/collection-notice/collection-notice.component.ts, fpincome/src/app/income-review/component/financial-input/financial-input.component.html, fpincome/src/app/income-review/pages/income/income.component.html, fpincome/src/version.GENERATED.ts
=> Accessibility fixes

fpincome/src/app/income-review/pages/confirmation/confirmation.component.html, fpincome/src/version.GENERATED.ts
=> fix: landmark confirmation page

fpincome/src/app/income-review/component/collection-notice/collection-notice.component.ts
=> fix: modal focus

captcha-service/package-lock.json, captcha-service/package.json, captcha-service/src/index.ts, captcha-service/tests/test.ts
Fix for memory leak issue.
Upgrade packages to fix vulnerabilities.
Possible known issue requires further evaluation: Captcha service crash in dev when requesting audio.
=> Captcha change integration

captcha-service/package-lock.json, captcha-service/package.json, captcha-service/src/index.ts, captcha-service/tests/test.ts
Reverts bcgov/MOH-FPC-Enrolment#33
=> Revert "Captcha change integration"

captcha-service/package-lock.json, captcha-service/package.json, captcha-service/src/index.ts, captcha-service/tests/test.ts
Integrate Memory Leak Fixes
Block incomming request for Audio when Memory over 256Mb
Log event when Audio blocked(winston.error)
Increment minor version
=> fix: integrate memory leak fixes

captcha-service/src/index.ts
=> chore: increase debug info

captcha-service/package.json, captcha-service/src/index.ts
fix: moved audio request memory restriction closer to the known cause of memory use spike
=> fix: moved memory restriction

captcha-service/package.json, captcha-service/src/index.ts
fix: changed memory limit on audio request
=> Captcha memory fixes

captcha-service/src/index.ts
=> chore: remove audio memory limit

captcha-service/package.json
=> chore: increment version number

cache-service/gulpfile.js, cache-service/openshift/README.md, cache-service/openshift/templates/build.yaml, cache-service/openshift/templates/deploy.yaml, cache-service/openshift/templates/old/msp-service-build.json, cache-service/openshift/templates/old/msp-service-deploy.json, cache-service/openshift/templates/old/msp-service-jenkins.json, cache-service/package-lock.json, cache-service/package.json, cache-service/src/backend.js, cache-service/src/base64encode.js, cache-service/src/cache.js, cache-service/src/index.js, cache-service/src/logSplunk.js, cache-service/src/timestamp.js, fpcare/openshift/templates/config.yaml, fpcare/openshift/templates/deploy.yaml, fpcare/src/environments/environment.prod.ts, openshift/templates/quickfpcare-to-all.yaml
=> Move cache service for FPCare

.github/workflows/cache-service-to-prod.yaml, .github/workflows/cache-service-to-test.yaml, .github/workflows/cache-service.yaml
=> Added cache-service to github workflow

fpincome/src/app/income-review/pages/home/home.component.html
=> fix: updated aside to fix accessibility

fpcare/src/app/modules/header-footer/fpcare-header/fpcare-header.component.html
Removes accessibility issue related to header
=> fix: remove double banner from header

fpincome/src/app/income-review/pages/income/income.component.html
=> fix: updated aria-label for calculate income page

fpcare/src/app/modules/financial-calculator/components/annual-deductible/annual-deductible.component.html
=> fix: ensure heading levels decrease by 1

fpcare/src/app/modules/core/components/date/date.component.html, fpcare/src/app/modules/core/components/phn-definition/phn-definition.component.html
a11y changes for eligibility page
=> fix: update attribute usage for a11y in eligibility page

fpcare/src/app/styles/overrides.scss
=> Updated css for Disabled continue button

fpcare/src/app/modules/core/components/results-framework/results-framework.component.html
Removed unused aria-attributes
=> Fpcare status a11y

fpincome/src/app/app.component.html, fpincome/src/app/income-review/income-review.component.html, fpincome/src/app/income-review/pages/consent/consent.component.html, fpincome/src/app/income-review/pages/home/home.component.html, fpincome/src/app/income-review/pages/income/income.component.html, fpincome/src/app/income-review/pages/personal-info/personal-info.component.html, fpincome/src/app/income-review/pages/review/review.component.html, fpincome/src/styles.scss
=> fix: add common-page-framework to FPC Income

fpcare/src/app/modules/core/components/consent-modal/consent-modal.component.html, fpcare/src/app/modules/core/components/date/date.component.html, fpcare/src/app/modules/core/components/name/name.component.html, fpcare/src/app/modules/core/components/phn/phn.component.html, fpcare/src/app/modules/core/components/results-framework/results-framework.component.html, fpcare/src/app/modules/core/components/results-framework/results-framework.component.ts, fpcare/src/app/modules/core/components/sin/sin.component.html, fpcare/src/app/modules/core/components/toggle/toggle.component.html, fpcare/src/app/modules/registration-status/components/request-status/registration-status.component.html, fpcare/src/app/modules/registration/pages/calculator/calculator.component.html, fpcare/src/app/modules/registration/pages/calculator/calculator.component.spec.ts, fpcare/src/app/modules/registration/pages/complete/complete.component.html, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html, fpcare/src/app/modules/registration/pages/review/review.component.html, fpcare/src/app/modules/registration/pages/review/review.component.ts, fpcare/src/app/styles/additions.scss
=> fix: updates to accessibility

fpcare/package-lock.json, fpcare/src/app/modules/core/components/sample-modal/sample-modal.component.html, fpcare/src/app/modules/core/components/sample-modal/sample-modal.component.scss, fpcare/src/app/modules/core/components/sample-modal/sample-modal.component.ts, fpcare/src/app/modules/registration/pages/calculator/calculator.component.html, fpcare/src/app/modules/registration/pages/children/children.component.html, fpcare/src/app/modules/registration/pages/review/review.component.html
=> fix: update disability info field and sample image modal component

fpcare/src/app/app.component.html, fpcare/src/app/modules/registration-status/components/request-status/registration-status.component.html, fpcare/src/app/modules/registration-status/components/status-results/status-results.component.html, fpcare/src/app/modules/registration/components/registration-container/registration-container.component.html, fpcare/src/app/modules/reprint-letters/components/request-cob/request-cob.component.html, fpcare/src/app/modules/reprint-letters/components/request-consent/request-consent.component.html, fpcare/src/app/modules/splash-page/page/splash-page/splash-page.component.html, fpcare/src/app/pages/error-page/error-page.component.html, fpcare/src/app/pages/home-page/home-page.component.html
=> fix: updated landmarks accessibiltiy

fpcare/src/app/modules/registration/pages/children/children.component.html, fpcare/src/app/modules/registration/pages/review/review.component.html
=> fix: added aria-label to edit and remove icons as per Ernessto

fpincome/src/app/app.component.html, fpincome/src/app/income-review/pages/consent/consent.component.html, fpincome/src/app/income-review/pages/home/home.component.html, fpincome/src/app/income-review/pages/income/income.component.html, fpincome/src/app/income-review/pages/personal-info/personal-info.component.html, fpincome/src/app/income-review/pages/review/review.component.html
=> fix: duplicate landmarks and screen reader doesnt read required fields

fpcare/package-lock.json, fpcare/package.json, fpincome/package-lock.json, fpincome/package.json
=> fix: upgraded karma version for FPCare and Income Review

fpincome/src/app/income-review/component/financial-input/financial-input.component.html
=> fix: added required true to financial input

fpcare/src/app/modules/core/components/consent-modal/consent-modal.component.html
=> Minor fix: information collection notice captcha is loaded when user navigates to the page

fpcare/src/app/modules/core/components/consent-modal/consent-modal.component.html, fpcare/src/app/modules/core/components/consent-modal/consent-modal.component.ts, fpcare/src/app/modules/registration/pages/calculator/calculator.component.html, fpcare/src/app/modules/registration/pages/children/children.component.html, fpcare/src/app/modules/registration/pages/complete/complete.component.html, fpcare/src/app/modules/registration/pages/eligibility/eligibility.component.html, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html, fpcare/src/app/modules/registration/pages/personal-info/personal-info.component.html, fpcare/src/app/modules/registration/pages/review/review.component.html
=> fix: updated consent modal and headings for accessibility

fpcare/src/app/modules/registration-status/components/request-status/registration-status.component.html, fpcare/src/app/modules/registration-status/components/request-status/registration-status.component.ts, fpcare/src/app/modules/registration/pages/calculator/calculator.component.html, fpcare/src/app/modules/registration/pages/calculator/calculator.component.ts, fpcare/src/app/modules/registration/pages/children/children.component.html, fpcare/src/app/modules/registration/pages/children/children.component.ts, fpcare/src/app/modules/registration/pages/complete/complete.component.html, fpcare/src/app/modules/registration/pages/complete/complete.component.ts, fpcare/src/app/modules/registration/pages/eligibility/eligibility.component.html, fpcare/src/app/modules/registration/pages/eligibility/eligibility.component.ts, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.ts, fpcare/src/app/modules/registration/pages/personal-info/personal-info.component.html, fpcare/src/app/modules/registration/pages/personal-info/personal-info.component.ts, fpcare/src/app/modules/registration/pages/registration-requirements/registration-requirements.component.html, fpcare/src/app/modules/registration/pages/registration-requirements/registration-requirements.component.ts, fpcare/src/app/modules/registration/pages/review/review.component.html, fpcare/src/app/modules/registration/pages/review/review.component.ts
=> fix: added tabbing for the h1 elements on every page in FPCare

fpincome/src/app/income-review/component/collection-notice/collection-notice.component.ts, fpincome/src/app/income-review/pages/consent/consent.component.html, fpincome/src/app/income-review/pages/consent/consent.component.ts, fpincome/src/app/income-review/pages/home/home.component.html, fpincome/src/app/income-review/pages/home/home.component.ts, fpincome/src/app/income-review/pages/income/income.component.html, fpincome/src/app/income-review/pages/income/income.component.ts, fpincome/src/app/income-review/pages/personal-info/personal-info.component.html, fpincome/src/app/income-review/pages/personal-info/personal-info.component.ts, fpincome/src/app/income-review/pages/review/review.component.html, fpincome/src/app/income-review/pages/review/review.component.ts
=> fix: added tabbing on headings on every page for FPincome

fpincome/src/app/income-review/pages/review/review.component.ts
=> fix: added ngAfterViewInit to fix the unsubscribe error from Review Page

fpcare/src/app/modules/registration/pages/complete/complete.component.html, fpcare/src/app/modules/registration/pages/registration-requirements/registration-requirements.component.html, fpcare/src/app/modules/registration/pages/review/review.component.html
=> fix: added missing main landmark and changed edit pencil icons into buttons

fpincome/src/app/income-review/component/review-container/review-container.component.html, fpincome/src/app/income-review/component/review-container/review-container.component.scss, fpincome/src/app/income-review/pages/home/home.component.html, fpincome/src/app/income-review/pages/review/review.component.html
=> Fpcirn 32 v2

fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html
=> fix: change Country to Jurisdiction

fpcare/src/app/modules/registration-status/components/request-status/registration-status.component.html, fpcare/src/app/modules/registration/pages/calculator/calculator.component.html, fpcare/src/app/modules/registration/pages/children/children.component.html, fpcare/src/app/modules/registration/pages/complete/complete.component.html, fpcare/src/app/modules/registration/pages/eligibility/eligibility.component.html, fpcare/src/app/modules/registration/pages/mailing-address/mailing-address.component.html, fpcare/src/app/modules/registration/pages/personal-info/personal-info.component.html, fpcare/src/app/modules/registration/pages/reg-results/reg-results.component.html, fpcare/src/app/modules/registration/pages/registration-requirements/registration-requirements.component.html, fpcare/src/app/modules/registration/pages/review/review.component.html, fpcare/src/app/pages/error-page/error-page.component.html, fpincome/src/app/income-review/component/review-container/review-container.component.html, fpincome/src/app/income-review/pages/consent/consent.component.html, fpincome/src/app/income-review/pages/home/home.component.html, fpincome/src/app/income-review/pages/income/income.component.html, fpincome/src/app/income-review/pages/personal-info/personal-info.component.html, fpincome/src/app/income-review/pages/review/review.component.html
=> Remove focus on headings

fpincome/src/app/income-review/pages/confirmation/confirmation.component.html, fpincome/src/app/income-review/pages/home/home.component.html
=> fix: minor issues with home and confirmation pages in FPIncome

fpincome/src/app/income-review/pages/confirmation/confirmation.component.html, fpincome/src/app/income-review/pages/home/home.component.html, fpincome/src/app/income-review/pages/home/home.component.ts
=> fix: removed tabindex in confirmation and updated headings in home page

fpincome/src/app/income-review/component/review-container/review-container.component.html, fpincome/src/app/income-review/pages/confirmation/confirmation.component.html, fpincome/src/app/income-review/pages/confirmation/confirmation.component.scss, fpincome/src/app/income-review/pages/confirmation/confirmation.component.ts
=> fix: minor screen readability fix in Confirmation Page

fpcare/package-lock.json, fpcare/package.json, fpcare/src/VERSION.generated.ts, fpcare/src/app/app-routing.module.ts, fpcare/src/app/app.component.ts, fpcare/src/app/pages/home-page/home-page.component.html, fpincome/package-lock.json
=> Redirect FPCare Registration to the new JHA Application

fpcare/package-lock.json, fpcare/package.json, fpcare/src/VERSION.generated.ts, fpcare/src/app/app.component.ts
Bug fix
/registration-status urls were being recognized as /registration urls
=> Fix redirect bug

address-service/package-lock.json, address-service/package.json, cache-service/package-lock.json, cache-service/package.json, msp-service/package-lock.json, msp-service/package.json, spa-env-server/package-lock.json, spa-env-server/package.json
=> JWT Vulnerability fix for FPCare and FPIncome

address-service/package-lock.json, address-service/package.json, cache-service/package-lock.json, cache-service/package.json, msp-service/package-lock.json, msp-service/package.json, spa-env-server/package-lock.json, spa-env-server/package.json
=> fixed: rollback jwt versions

address-service/package-lock.json, address-service/package.json, cache-service/package-lock.json, cache-service/package.json, msp-service/package-lock.json, msp-service/package.json, spa-env-server/package-lock.json, spa-env-server/package.json
=> fixed: updated jwt to v9.0.0

itrf/package-lock.json, itrf/package.json, itrf/src/App.vue, itrf/src/components/ProgressBar.vue, itrf/src/router/index.js, itrf/src/services/page-state-service.js, itrf/src/services/spa-env-service.js, itrf/src/settings.js, itrf/src/views/DeclarationPage.vue, itrf/src/views/GetStartedPage.vue, itrf/src/views/PersonalInfoPage.vue, itrf/src/views/SubmissionErrorPage.vue, itrf/src/views/SubmissionPage.vue, itrf/tests/unit/services/page-state-service.spec.js, itrf/vite.config.js
=> HCS-351: Get Started Page

itrf/src/views/DeclarationPage.vue, itrf/src/views/GetStartedPage.vue, itrf/src/views/PersonalInfoPage.vue, itrf/src/views/SubmissionPage.vue
=> fix: updated text changes from Ernesto's wireframe

.github/workflows/itrf-web.yaml, itrf/openshift/templates/build.yaml, itrf/openshift/templates/config.yaml, itrf/openshift/templates/deploy.yaml
- add itrf build workflow
- update fpc --> itrf in the build, config, deploy templates
- add other information needed to create all of the OpenShift objects
=> DE 430: Implement OpenShift Architecture

itrf/openshift/templates/build.yaml, itrf/openshift/templates/config.yaml
- fix build.yaml to use a Docker image rather than a (currently non-existent) OpenShift imagestream
- comment out unneeded parameters
- fix config.yaml to accommodate a splunk auth token in the nginx setup
=> DE 430 Continued: OpenShift template cleanup

itrf/src/helpers/scroll.js, itrf/src/views/GetStartedPage.vue, itrf/src/views/PersonalInfoPage.vue, itrf/tests/helpers/scroll.spec.js
=> feat: add scroll.js

itrf/index.html, itrf/src/App.vue, itrf/src/router/index.js, itrf/src/services/api-service.js, itrf/src/views/DeclarationPage.vue, itrf/src/views/GetStartedPage.vue, itrf/src/views/PersonalInfoPage.vue
=> fix: removed declaration page and updated title

itrf/src/services/api-service.js, msp-service/src/index.js
=> Test logs in msp-service in DEV

msp-service/src/logSplunk.js
=> fix: update hostname in logSplunk.js

msp-service/package-lock.json, msp-service/package.json, msp-service/src/index.js
=> Downgrade jwt

msp-service/src/index.js
=> fix: added a proxySetHeader to accomodate the basic auth

msp-service/src/index.js
=> fix: add logs to on proxy request

msp-service/src/index.js
=> fix: replaxe the headers from proxyReq to req

msp-service/src/index.js
=> fix: refactor http proxy middleware in msp-service

msp-service/src/index.js
=> Api auth issue v5

msp-service/src/index.js
=> fix: test to see if auth works in only FPC

msp-service/src/index.js
=> Api service auth v7

msp-service/src/index.js
=> fix: remove plus sign in msp-service

msp-service/src/index.js
=> fix: capitalize A in authorization

msp-service/src/index.js
=> fix: change auth to proxyReq

msp-service/src/index.js
=> fix: remove word basic in setHeader

msp-service/src/index.js
=> fix: add req headers for basic auth

msp-service/src/index.js
=> fix: changed to user for basic auth

msp-service/src/index.js
=> fix: try to add req.auth

msp-service/src/index.js
=> fix: created two proxies for msp-service

msp-service/package-lock.json, msp-service/package.json, msp-service/src/index.js
=> fix: use createProxyMiddleware

msp-service/src/index.js
=> fix: use proxyReq setHeader again

msp-service/src/index.js
=> fix: add targetAuth

msp-service/src/index.js
=> fix: use a separate function for authorization

msp-service/src/index.js
=> fix: put function inside onProxyReq

msp-service/src/index.js
=> fix: use Bearer and proxyReq.setHeader

msp-service/src/index.js
=> fix: change bearer to basic

msp-service/src/index.js
=> fix: msp-service clean up

itrf/package-lock.json, itrf/package.json, msp-service/package-lock.json, msp-service/package.json
Version bump for ITRF and MSP-service
=> Version bump (ITRF -> 0.1.0, MSP-service -> 1.2.0)

msp-service/openshift/templates/deploy.yaml
This is an OpenShift template change, so application checks are not required
=> Add ITRF template items to deploy.yaml

itrf/src/helpers/date.js, itrf/src/router/index.js, itrf/src/services/log-service.js, itrf/src/views/GetStartedPage.vue, itrf/src/views/MaintenancePage.vue, itrf/src/views/PersonalInfoPage.vue, itrf/src/views/SubmissionPage.vue, itrf/tests/unit/views/GetStartedPage.spec.js, itrf/tests/unit/views/MaintenancePage.spec.js, itrf/tests/unit/views/PersonalInfoPage.spec.js, itrf/tests/unit/views/SubmissionPage.spec.js
* Adds logging to the ITRF application + accompanying test updates
* Small bug fix: remove code disabling the loading animation after the validatePerson check (so it continues the loading animation through the submitForm call)
`npm audit --production` showed no vulnerabilities
`npm run build` passes
`npm run format` was run (prettier)
`npm run test:e2e` passes in Chrome, Firefox, and Edge
=> ITRF application logging, bug fixes

itrf/src/views/GetStartedPage.vue, itrf/src/views/PersonalInfoPage.vue
=> Accessibility Issues

fpcare/package-lock.json, fpcare/package.json, fpcare/src/VERSION.generated.ts, fpcare/src/app/services/api-service.service.ts, fpcare/src/app/services/logger.service.ts, fpcare/src/app/services/spa-env.service.ts
=> Remove unnecessary logs in FPC

itrf/src/views/GetStartedPage.vue
=> fix: changed the label from <p> to <Radio>

itrf/src/views/PersonalInfoPage.vue, itrf/src/views/SubmissionPage.vue
=> Personal Info and Submission Page accessibility fixes

itrf/src/views/PersonalInfoPage.vue
=> fix: add aria-label in Personal Info Page

itrf/src/views/PersonalInfoPage.vue
=> add handleBlurField for Personal Info Page fields

itrf/src/views/PersonalInfoPage.vue
Add code disabling the isLoading spinner when it receives an error
E2E tests all pass
=> Submit button fix (ITRF)

itrf/package-lock.json, itrf/package.json
=> Version bump (ITRF 0.1.0 -> 0.1.1)
